class Error(Exception):
	pass

class NetworkError(Error):
	pass